font.body=Source Han Sans
font.medium=Source Han Sans
font.heading=Noto Serif
font.monospace=monospace

text.size.default.sp=16
text.size.noise.sp=15
text.size.focus.min.sp=18
text.size.focus.scale.sp=20

line.spacing.default=1.5
line.spacing.noise=1.5
line.spacing.focus=1.5
text.letter.spacing.em=0.01

list.indent.input.unit.spaces=6
list.indent.output.unit.spaces=6
list.indent.max.depth=8
list.indent.tab.spaces=6

markwon.table.cell.padding=24
markwon.table.border.width=2
markwon.block.margin=48
markwon.bullet.width=18
#markwon.bullet.stroke.width=2
markwon.code.block.margin=10
markwon.blockquote.width=8
markwon.heading.break.height=10
markwon.heading.text.multipliers=1.80,1.60,1.40,1.25,1.12,1.0
markwon.latex.text.size.sp=48

spacing.heading.top.dp=12
spacing.heading.bottom.dp=0
spacing.blockquote.top.dp=14
spacing.default.top.dp=6
spacing.default.bottom.dp=6
spacing.indent.level.dp=24
spacing.subblock.top.dp=6
spacing.subblock.bottom.dp=6
noise.chevron.color=#8DA4B5
noise.chevron.rotate.duration.ms=220
