# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from protos import fusion_service_pb2 as protos_dot_fusion__service__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in protos/fusion_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FusionComputeServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ExtractFeatures = channel.unary_unary(
                '/com.mvp.module2.fusion.grpc.FusionComputeService/ExtractFeatures',
                request_serializer=protos_dot_fusion__service__pb2.FeatureRequest.SerializeToString,
                response_deserializer=protos_dot_fusion__service__pb2.FeatureResponse.FromString,
                _registered_method=True)
        self.Ping = channel.unary_unary(
                '/com.mvp.module2.fusion.grpc.FusionComputeService/Ping',
                request_serializer=protos_dot_fusion__service__pb2.Empty.SerializeToString,
                response_deserializer=protos_dot_fusion__service__pb2.HealthStatus.FromString,
                _registered_method=True)
        self.SelectBestFrame = channel.unary_unary(
                '/com.mvp.module2.fusion.grpc.FusionComputeService/SelectBestFrame',
                request_serializer=protos_dot_fusion__service__pb2.FrameSelectionRequest.SerializeToString,
                response_deserializer=protos_dot_fusion__service__pb2.FrameSelectionResponse.FromString,
                _registered_method=True)
        self.ComputeFrameHash = channel.unary_unary(
                '/com.mvp.module2.fusion.grpc.FusionComputeService/ComputeFrameHash',
                request_serializer=protos_dot_fusion__service__pb2.FrameHashRequest.SerializeToString,
                response_deserializer=protos_dot_fusion__service__pb2.FrameHashResponse.FromString,
                _registered_method=True)
        self.DetectFaults = channel.unary_unary(
                '/com.mvp.module2.fusion.grpc.FusionComputeService/DetectFaults',
                request_serializer=protos_dot_fusion__service__pb2.DetectFaultsRequest.SerializeToString,
                response_deserializer=protos_dot_fusion__service__pb2.DetectFaultsResponse.FromString,
                _registered_method=True)
        self.GenerateEnhancementText = channel.unary_unary(
                '/com.mvp.module2.fusion.grpc.FusionComputeService/GenerateEnhancementText',
                request_serializer=protos_dot_fusion__service__pb2.GenerateTextRequest.SerializeToString,
                response_deserializer=protos_dot_fusion__service__pb2.GenerateTextResponse.FromString,
                _registered_method=True)
        self.OptimizeMaterials = channel.unary_unary(
                '/com.mvp.module2.fusion.grpc.FusionComputeService/OptimizeMaterials',
                request_serializer=protos_dot_fusion__service__pb2.OptimizeMaterialsRequest.SerializeToString,
                response_deserializer=protos_dot_fusion__service__pb2.OptimizeMaterialsResponse.FromString,
                _registered_method=True)


class FusionComputeServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ExtractFeatures(self, request, context):
        """1. Submit a video for feature extraction (Sync/Blocking)
        Java calls this to trigger Python processing.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Ping(self, request, context):
        """2. Health Check (for Java Sentinel/Resilience4j)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SelectBestFrame(self, request, context):
        """3. Select the best screenshot from a video segment
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ComputeFrameHash(self, request, context):
        """4. Compute perceptual hash for a list of frames (for MaterialOptimizer)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DetectFaults(self, request, context):
        """5. Strict Parity: Fault Detection utilizing Python LLM
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateEnhancementText(self, request, context):
        """6. Strict Parity: Cognitive Text Generation
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OptimizeMaterials(self, request, context):
        """7. Strict Parity: Global Material Optimization (Clustering & Deduplication)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FusionComputeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ExtractFeatures': grpc.unary_unary_rpc_method_handler(
                    servicer.ExtractFeatures,
                    request_deserializer=protos_dot_fusion__service__pb2.FeatureRequest.FromString,
                    response_serializer=protos_dot_fusion__service__pb2.FeatureResponse.SerializeToString,
            ),
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=protos_dot_fusion__service__pb2.Empty.FromString,
                    response_serializer=protos_dot_fusion__service__pb2.HealthStatus.SerializeToString,
            ),
            'SelectBestFrame': grpc.unary_unary_rpc_method_handler(
                    servicer.SelectBestFrame,
                    request_deserializer=protos_dot_fusion__service__pb2.FrameSelectionRequest.FromString,
                    response_serializer=protos_dot_fusion__service__pb2.FrameSelectionResponse.SerializeToString,
            ),
            'ComputeFrameHash': grpc.unary_unary_rpc_method_handler(
                    servicer.ComputeFrameHash,
                    request_deserializer=protos_dot_fusion__service__pb2.FrameHashRequest.FromString,
                    response_serializer=protos_dot_fusion__service__pb2.FrameHashResponse.SerializeToString,
            ),
            'DetectFaults': grpc.unary_unary_rpc_method_handler(
                    servicer.DetectFaults,
                    request_deserializer=protos_dot_fusion__service__pb2.DetectFaultsRequest.FromString,
                    response_serializer=protos_dot_fusion__service__pb2.DetectFaultsResponse.SerializeToString,
            ),
            'GenerateEnhancementText': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateEnhancementText,
                    request_deserializer=protos_dot_fusion__service__pb2.GenerateTextRequest.FromString,
                    response_serializer=protos_dot_fusion__service__pb2.GenerateTextResponse.SerializeToString,
            ),
            'OptimizeMaterials': grpc.unary_unary_rpc_method_handler(
                    servicer.OptimizeMaterials,
                    request_deserializer=protos_dot_fusion__service__pb2.OptimizeMaterialsRequest.FromString,
                    response_serializer=protos_dot_fusion__service__pb2.OptimizeMaterialsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'com.mvp.module2.fusion.grpc.FusionComputeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('com.mvp.module2.fusion.grpc.FusionComputeService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FusionComputeService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ExtractFeatures(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/com.mvp.module2.fusion.grpc.FusionComputeService/ExtractFeatures',
            protos_dot_fusion__service__pb2.FeatureRequest.SerializeToString,
            protos_dot_fusion__service__pb2.FeatureResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/com.mvp.module2.fusion.grpc.FusionComputeService/Ping',
            protos_dot_fusion__service__pb2.Empty.SerializeToString,
            protos_dot_fusion__service__pb2.HealthStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SelectBestFrame(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/com.mvp.module2.fusion.grpc.FusionComputeService/SelectBestFrame',
            protos_dot_fusion__service__pb2.FrameSelectionRequest.SerializeToString,
            protos_dot_fusion__service__pb2.FrameSelectionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ComputeFrameHash(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/com.mvp.module2.fusion.grpc.FusionComputeService/ComputeFrameHash',
            protos_dot_fusion__service__pb2.FrameHashRequest.SerializeToString,
            protos_dot_fusion__service__pb2.FrameHashResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DetectFaults(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/com.mvp.module2.fusion.grpc.FusionComputeService/DetectFaults',
            protos_dot_fusion__service__pb2.DetectFaultsRequest.SerializeToString,
            protos_dot_fusion__service__pb2.DetectFaultsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateEnhancementText(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/com.mvp.module2.fusion.grpc.FusionComputeService/GenerateEnhancementText',
            protos_dot_fusion__service__pb2.GenerateTextRequest.SerializeToString,
            protos_dot_fusion__service__pb2.GenerateTextResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def OptimizeMaterials(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/com.mvp.module2.fusion.grpc.FusionComputeService/OptimizeMaterials',
            protos_dot_fusion__service__pb2.OptimizeMaterialsRequest.SerializeToString,
            protos_dot_fusion__service__pb2.OptimizeMaterialsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
