# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import video_processing_pb2 as video__processing__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in video_processing_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class VideoProcessingServiceStub(object):
    """==========================================
    主服务定义
    ==========================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.DownloadVideo = channel.unary_unary(
                '/videoprocessing.VideoProcessingService/DownloadVideo',
                request_serializer=video__processing__pb2.DownloadRequest.SerializeToString,
                response_deserializer=video__processing__pb2.DownloadResponse.FromString,
                _registered_method=True)
        self.TranscribeVideo = channel.unary_unary(
                '/videoprocessing.VideoProcessingService/TranscribeVideo',
                request_serializer=video__processing__pb2.TranscribeRequest.SerializeToString,
                response_deserializer=video__processing__pb2.TranscribeResponse.FromString,
                _registered_method=True)
        self.ProcessStage1 = channel.unary_unary(
                '/videoprocessing.VideoProcessingService/ProcessStage1',
                request_serializer=video__processing__pb2.Stage1Request.SerializeToString,
                response_deserializer=video__processing__pb2.Stage1Response.FromString,
                _registered_method=True)
        self.AnalyzeSemanticUnits = channel.unary_unary(
                '/videoprocessing.VideoProcessingService/AnalyzeSemanticUnits',
                request_serializer=video__processing__pb2.AnalyzeRequest.SerializeToString,
                response_deserializer=video__processing__pb2.AnalyzeResponse.FromString,
                _registered_method=True)
        self.AssembleRichText = channel.unary_unary(
                '/videoprocessing.VideoProcessingService/AssembleRichText',
                request_serializer=video__processing__pb2.AssembleRequest.SerializeToString,
                response_deserializer=video__processing__pb2.AssembleResponse.FromString,
                _registered_method=True)
        self.ValidateCVBatch = channel.unary_stream(
                '/videoprocessing.VideoProcessingService/ValidateCVBatch',
                request_serializer=video__processing__pb2.CVValidationRequest.SerializeToString,
                response_deserializer=video__processing__pb2.CVValidationResponse.FromString,
                _registered_method=True)
        self.ClassifyKnowledgeBatch = channel.unary_unary(
                '/videoprocessing.VideoProcessingService/ClassifyKnowledgeBatch',
                request_serializer=video__processing__pb2.KnowledgeClassificationRequest.SerializeToString,
                response_deserializer=video__processing__pb2.KnowledgeClassificationResponse.FromString,
                _registered_method=True)
        self.GenerateMaterialRequests = channel.unary_unary(
                '/videoprocessing.VideoProcessingService/GenerateMaterialRequests',
                request_serializer=video__processing__pb2.GenerateMaterialRequestsRequest.SerializeToString,
                response_deserializer=video__processing__pb2.GenerateMaterialRequestsResponse.FromString,
                _registered_method=True)
        self.AnalyzeWithVL = channel.unary_unary(
                '/videoprocessing.VideoProcessingService/AnalyzeWithVL',
                request_serializer=video__processing__pb2.VLAnalysisRequest.SerializeToString,
                response_deserializer=video__processing__pb2.VLAnalysisResponse.FromString,
                _registered_method=True)
        self.ReleaseCVResources = channel.unary_unary(
                '/videoprocessing.VideoProcessingService/ReleaseCVResources',
                request_serializer=video__processing__pb2.ReleaseResourcesRequest.SerializeToString,
                response_deserializer=video__processing__pb2.ReleaseResourcesResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/videoprocessing.VideoProcessingService/HealthCheck',
                request_serializer=video__processing__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=video__processing__pb2.HealthCheckResponse.FromString,
                _registered_method=True)


class VideoProcessingServiceServicer(object):
    """==========================================
    主服务定义
    ==========================================

    """

    def DownloadVideo(self, request, context):
        """步骤1: 下载视频 (IO密集 - Python)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TranscribeVideo(self, request, context):
        """步骤2: Whisper转录 (GPU/CPU密集 - Python)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ProcessStage1(self, request, context):
        """步骤3: Stage1处理(步骤1-6) (LLM API调用 - Python)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AnalyzeSemanticUnits(self, request, context):
        """🔑 V2: Module2 拆分为两阶段
        步骤4: Module2 Phase2A - 语义分析 + 时间戳提取 (不执行FFmpeg)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AssembleRichText(self, request, context):
        """步骤5 由 Java 执行 FFmpeg

        步骤6: Module2 Phase2B - Vision AI验证 + 富文本组装 (使用外部截图)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ValidateCVBatch(self, request, context):
        """🚀 V3: CV验证批量并行处理 (Java编排调用 - 流式返回)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClassifyKnowledgeBatch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateMaterialRequests(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AnalyzeWithVL(self, request, context):
        """🔥 V7: VL-Based Analysis (使用 Qwen3-VL-Plus 直接分析视频，跳过 CV/LLM)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReleaseCVResources(self, request, context):
        """🚀 V6: 资源释放
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """健康检查
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VideoProcessingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'DownloadVideo': grpc.unary_unary_rpc_method_handler(
                    servicer.DownloadVideo,
                    request_deserializer=video__processing__pb2.DownloadRequest.FromString,
                    response_serializer=video__processing__pb2.DownloadResponse.SerializeToString,
            ),
            'TranscribeVideo': grpc.unary_unary_rpc_method_handler(
                    servicer.TranscribeVideo,
                    request_deserializer=video__processing__pb2.TranscribeRequest.FromString,
                    response_serializer=video__processing__pb2.TranscribeResponse.SerializeToString,
            ),
            'ProcessStage1': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessStage1,
                    request_deserializer=video__processing__pb2.Stage1Request.FromString,
                    response_serializer=video__processing__pb2.Stage1Response.SerializeToString,
            ),
            'AnalyzeSemanticUnits': grpc.unary_unary_rpc_method_handler(
                    servicer.AnalyzeSemanticUnits,
                    request_deserializer=video__processing__pb2.AnalyzeRequest.FromString,
                    response_serializer=video__processing__pb2.AnalyzeResponse.SerializeToString,
            ),
            'AssembleRichText': grpc.unary_unary_rpc_method_handler(
                    servicer.AssembleRichText,
                    request_deserializer=video__processing__pb2.AssembleRequest.FromString,
                    response_serializer=video__processing__pb2.AssembleResponse.SerializeToString,
            ),
            'ValidateCVBatch': grpc.unary_stream_rpc_method_handler(
                    servicer.ValidateCVBatch,
                    request_deserializer=video__processing__pb2.CVValidationRequest.FromString,
                    response_serializer=video__processing__pb2.CVValidationResponse.SerializeToString,
            ),
            'ClassifyKnowledgeBatch': grpc.unary_unary_rpc_method_handler(
                    servicer.ClassifyKnowledgeBatch,
                    request_deserializer=video__processing__pb2.KnowledgeClassificationRequest.FromString,
                    response_serializer=video__processing__pb2.KnowledgeClassificationResponse.SerializeToString,
            ),
            'GenerateMaterialRequests': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateMaterialRequests,
                    request_deserializer=video__processing__pb2.GenerateMaterialRequestsRequest.FromString,
                    response_serializer=video__processing__pb2.GenerateMaterialRequestsResponse.SerializeToString,
            ),
            'AnalyzeWithVL': grpc.unary_unary_rpc_method_handler(
                    servicer.AnalyzeWithVL,
                    request_deserializer=video__processing__pb2.VLAnalysisRequest.FromString,
                    response_serializer=video__processing__pb2.VLAnalysisResponse.SerializeToString,
            ),
            'ReleaseCVResources': grpc.unary_unary_rpc_method_handler(
                    servicer.ReleaseCVResources,
                    request_deserializer=video__processing__pb2.ReleaseResourcesRequest.FromString,
                    response_serializer=video__processing__pb2.ReleaseResourcesResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=video__processing__pb2.HealthCheckRequest.FromString,
                    response_serializer=video__processing__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'videoprocessing.VideoProcessingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('videoprocessing.VideoProcessingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class VideoProcessingService(object):
    """==========================================
    主服务定义
    ==========================================

    """

    @staticmethod
    def DownloadVideo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/videoprocessing.VideoProcessingService/DownloadVideo',
            video__processing__pb2.DownloadRequest.SerializeToString,
            video__processing__pb2.DownloadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TranscribeVideo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/videoprocessing.VideoProcessingService/TranscribeVideo',
            video__processing__pb2.TranscribeRequest.SerializeToString,
            video__processing__pb2.TranscribeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ProcessStage1(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/videoprocessing.VideoProcessingService/ProcessStage1',
            video__processing__pb2.Stage1Request.SerializeToString,
            video__processing__pb2.Stage1Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AnalyzeSemanticUnits(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/videoprocessing.VideoProcessingService/AnalyzeSemanticUnits',
            video__processing__pb2.AnalyzeRequest.SerializeToString,
            video__processing__pb2.AnalyzeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AssembleRichText(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/videoprocessing.VideoProcessingService/AssembleRichText',
            video__processing__pb2.AssembleRequest.SerializeToString,
            video__processing__pb2.AssembleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ValidateCVBatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/videoprocessing.VideoProcessingService/ValidateCVBatch',
            video__processing__pb2.CVValidationRequest.SerializeToString,
            video__processing__pb2.CVValidationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClassifyKnowledgeBatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/videoprocessing.VideoProcessingService/ClassifyKnowledgeBatch',
            video__processing__pb2.KnowledgeClassificationRequest.SerializeToString,
            video__processing__pb2.KnowledgeClassificationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateMaterialRequests(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/videoprocessing.VideoProcessingService/GenerateMaterialRequests',
            video__processing__pb2.GenerateMaterialRequestsRequest.SerializeToString,
            video__processing__pb2.GenerateMaterialRequestsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AnalyzeWithVL(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/videoprocessing.VideoProcessingService/AnalyzeWithVL',
            video__processing__pb2.VLAnalysisRequest.SerializeToString,
            video__processing__pb2.VLAnalysisResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReleaseCVResources(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/videoprocessing.VideoProcessingService/ReleaseCVResources',
            video__processing__pb2.ReleaseResourcesRequest.SerializeToString,
            video__processing__pb2.ReleaseResourcesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/videoprocessing.VideoProcessingService/HealthCheck',
            video__processing__pb2.HealthCheckRequest.SerializeToString,
            video__processing__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
